development: &default
  adapter: postgresql
  database: identity-partners_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(Figaro.env.db_pool || 5) %>
  reaping_frequency: <%= Integer(Figaro.env.dp_reaping_frequency || 10) %>
  timeout: 5000
  host: localhost

test:
  <<: *default
  database: identity-partners_test

production:
  adapter: postgresql
  encoding: utf8
  database: identity-partners_production
  pool: 5
