test: &default
  oidc_sp_issuer: "<%= Figaro.env.oidc_sp_issuer %>"
  idp_url: "<%= Figaro.env.idp_url %>"
  partners_url: "<%= Figaro.env.partners_url %>"

development:
  <<: *default

production:
  <<: *default
